apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: baota
  labels:
    app: baota
spec:
  storageClassName: rook-ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
apiVersion: apps/v1
kind: Deployment
metadata:
  name: baota
  labels:
    app: baota
spec:
  replicas: 1
  selector:
    matchLabels:
      app: baota
  template:
    metadata:
      labels:
        app: baota
    spec:
      containers:
      - name: baota
        image: pch18/baota:lamp
      volumeMounts:
      - name: baota
        mountPath: /www
    volumes:
    - name: baota
      persistentVolumeClaim:
        claimName: baota
   
